andes/mobile-app

- config.xml
- src/pages/vacunas/vacunas.html
- src/pages/vacunas/vacunas.ts
- src/providers/vacunas/vacunas.ts
Cambios en service para buscar vacunas del paciente.
Buscar y almacenar en localStorage vacunas del paciente que tengan un matching del 90%.
> Validacion vacunas

- config.xml
- package.json
- src/app/app.module.ts
- src/pages/profile/paciente/profile-paciente.html
- src/pages/profile/paciente/profile-paciente.scss
- src/pages/profile/paciente/profile-paciente.ts
- src/providers/constantes.ts
- src/providers/google-maps/map.ts
Nueva funcionalidad para indicar donde vive y donde trabaja un usuario de la app mobile.
Se ingresa a través de los datos personales y luego carga en una page que se reutiliza.
> Donde vivo donde trabajo

- src/pages/profile/paciente/donde-vivo-donde-trabajo/donde-vivo-donde-trabajo.html
- src/pages/profile/paciente/donde-vivo-donde-trabajo/donde-vivo-donde-trabajo.scss
- src/pages/profile/paciente/donde-vivo-donde-trabajo/donde-vivo-donde-trabajo.ts
Archivos faltantes de donde vivo y donde trabajo
> Archivos donde vivo donde trabajo

- src/pages/profesional/form-terapeutico/form-terapeutico-detalle.html
- src/pages/profesional/form-terapeutico/form-terapeutico.html
- src/pages/profesional/form-terapeutico/form-terapeutico.ts
- fix issue #20
- agrego botones para limpiar selects de formulario terapéutico.
- **Es necesario mergear un PR en la api branch fix-controller-form-terapeutico**
>  Formulario terapéutico: fix #20

- src/pages/datos-utiles/campanias/campanias-list.ts
> Se agrega loading cuando busca campañas

- src/pages/datos-utiles/centros-salud/list/list.ts
- src/pages/datos-utiles/centros-salud/map/map.html
1. Habilitar botón "Ver más" en la ventana de información de todos los centros en el mapa.
2. Filtrar "Centros de salud cercanos" según los que se están mostrando (Atributo "showMapa" en true en DB).
3. Corregir la ubicación al navegar al centro cercano. Decía (undefined; undefined) y ahora pasa bien la latitud y longitud
> Lista de prestaciones - Centros de salud cercanos

- src/app/app.component.ts
- src/assets/files/data.json
- Agregamos regenerar indices.
- Agregamos filtrado de % de ocupación de camas: Problemas filtro.
> feat(gestion): regenerar indices

- .github/CODEOWNERS
- .github/pull_request_template.md
- config.xml
- config/prod.xml
- package.json
- Add codeowners file.
- Add pull request template.
> feat(mobileApp): add github configurations

- src/theme/main.scss
ISSUE #75 
Se modifican los estilos para que se muestre de forma correcta el selector de localidades en farmacias de turno
> MOBILE-APP: arreglo de estilo de selector de localidad en farmacias de turno

- src/pages/gestion/principal.ts
https://proyectos.andes.gob.ar/browse/AM-13
1. Se agrega un llamado a actualizar el campo _lastLogin_ con el parametro _new Date_
> App de gestión - Registrar accesos de usuarios

- src/pages/datos-utiles/centros-salud/centros-salud-prestaciones.html
- src/pages/datos-utiles/centros-salud/map/map.html
- src/theme/main.scss
https://proyectos.andes.gob.ar/browse/TM-4
1. Modificación  para mostrar nombre y detalle de las ofertas prestacionales de cada efector
2. Se agrega la clase andes-capitalize para mostrar las ofertas prestacionales en el mapa con la primer letra en Mayuscula
3. Creación de Script para obtener las agendas de cada efector durante el mes de enero del 2020 e insertar las ofertas prestacionales según corresponda en cada efector
Script:
[ofertasPrestacionales.zip](https://github.com/andes/mobile-app/files/4268030/ofertasPrestacionales.zip)
Nota: Reemplaza al PR
https://github.com/andes/mobile-app/pull/84
> Migración inicial de ofertas prestacionales

- src/pages/datos-utiles/numeros-emergencia/numeros-utiles.html
Corrige call a 0800 para parsear un string
1. Corrige call a 0800 para pasar un string
> fix(home): corrige call 0800

- src/pages/datos-utiles/feed-noticias/feed-noticias.ts
https://proyectos.andes.gob.ar/browse/AM-29
1. Se obtiene _'content:encoded'_ del _element_ que es donde vienen las imagenes.
> Noticias: Al ingresar a notisalud no muestra las imagenes

- src/pages/turnos/calendario/turnos-calendario.ts
https://proyectos.andes.gob.ar/browse/CIT-42
1. Se envía el telefono del paciente si tiene un celular dentro del array de contactos
> MOBILE-APP: envío de teléfono en el paciente al guardar un turno

- src/pages/login/login.ts
https://proyectos.andes.gob.ar/browse/AM-26
1. Se agrega linea para pasar el email del usuario a minúscula antes de enviarlo a la API
> LOGIN: enviar email en minuscula

- src/pages/profesional/form-terapeutico/form-terapeutico.html
- src/pages/profesional/form-terapeutico/form-terapeutico.ts
https://proyectos.andes.gob.ar/browse/AM-16
1. Se agrega la funcion _(ionInput)_  para que al ocurrir un evento de teclado llame a la funcion _busquedaMedicamentos($event)_.
2. Se agrega la funcion _busquedaMedicamentos(event)_ que devuelve la lista de medicamentos que _machean_ con el evento ingresado.
3. Se solucionan errores de linteo.
> Formulario-terapeutico: Búsqueda en formulario terapeutico

- src/app/app.module.ts
- src/pages/login/disclaimers/accept-disclaimer.html
- src/pages/login/disclaimers/accept-disclaimer.ts
- src/pages/login/login.ts
- src/providers/auth/auth.ts
- src/providers/auth/disclaimer.ts
1. Se suma la pantalla para aceptar el disclaimer activo
Se agrega la colección disclaimers. Esto se indica en el PR correspondiente en la API.
> MOBILE-APP: pantalla de disclaimers para profesionales

- src/pages/registro/informacion-validacion/informacion-validacion.html
- src/pages/registro/informacion-validacion/informacion-validacion.scss
https://proyectos.andes.gob.ar/browse/AM-39
1. Se modifica la pantalla "Primer Paso" con los datos actuales con los que un usuario debe activar la app mobile.
- La pantalla no quedo idéntica al mockup ya que los iconos y fuentes no se encuentran en el paquete de Ionic. Fue consensuado con Andres el diseño que quedo.
-  Se deja comentado el código en informacion-validacion.html para volver a usarlo cuando finalice la pandemia.
> Validacion: Se actualiza pantalla "Primer Paso"

- src/pages/login/disclaimers/accept-disclaimer.html
- src/pages/registro/informacion-validacion/informacion-validacion.html
corregir Disclaimer para que el texto se vea blanco.
1. Se corrigió una clase
> fix(disclaimer): corrige color de fuente

- src/pages/registro/recuperar-password/recuperar-password.ts
- src/pages/registro/verifica-codigo/verifica-codigo.ts
https://proyectos.andes.gob.ar/browse/AM-45
Al momento de querer recuperar el password de un usuario con email con el caracter '_' el botón recuperar contraseña no respondía.
1. Se modifica el regex que estaba por el que utiliza angular para hacer la verificación de los emails para que acepte emails con el caracter '_' tanto en el componente recuperar contraseña como el de enviar el código.
> Usuario:Error al recuperar contraseña

- src/pages/profile/paciente/profile-contactos.ts
https://proyectos.andes.gob.ar/browse/AM-42
1. Se elimina la comprobación por la longitud del objeto tanto en el teléfono como en el email y se pregunta por el objeto en si, ya que si el paciente no tiene guardado en la colección _paciente_ un teléfono o un email, arroja un error al querer encontrar la longitud. Con este cambio se sigue comprobando que exista el objeto y en el caso que no haya nada guardado no arroja error.
-  x] No
> CONTACTOS-PERFIL: Error al editar teléfono

- src/app/app.html
- src/app/app.module.ts
- src/pages/home/home.ts
- src/pages/turnos/historial/historial-turnos.html
- src/pages/turnos/historial/historial-turnos.scss
- src/pages/turnos/historial/historial-turnos.ts
- src/pages/turnos/turnos.html
- src/pages/turnos/turnos.ts
- src/pipes/enumerar.pipe.ts
- src/providers/turnos.ts
https://proyectos.andes.gob.ar/browse/AM-40
1. Se agrega el componente _historial-turnos_ y la vista _historial-turnos_ para visualizar el historial de turnos de un paciente.
2. En _app.html_ se le agrega el _id='principal'_ para que funcionen correctamente los menúes hamburguesa.
3. en _turnos.html_ se agrega un menú hamburguesa que da la opción de ingresar al historial de turnos o reportar un bug.
4. Se agrega el pipe _enumerar_, para mostrar correctamente los profesionales según el turno.
5. Se agrega en el provider de turnos, la ruta hacia la api para obtener el historial.
> Turnos: Visualizar Historial de turnos

- src/pages/home/home.ts
- src/providers/auth/auth.ts
Controlar si el token del profesional expiró y en ese caso redirige al login
1. Agrega control de token expirado en la pagina home
> fix(Profesional): Controla la expiración del token

- src/pages/home/home.ts
Se elimina ruteo que enviaba al login en el load del home en caso de que el token hubiera expirado. En ese caso debe quedar en el home de bienvenida.
> fix(ruteo): Elimina ruteo a pantalla de login para que siga yendo al home

- src/app/app.module.ts
- src/pages/historia-salud/categorias/detalle-categoria.html
- src/pages/historia-salud/categorias/detalle-categoria.ts
- src/pages/historia-salud/historia-salud.html
- src/pages/historia-salud/historia-salud.ts
- src/pages/home/home.html
- src/pages/home/home.ts
- src/pages/login/disclaimers/accept-disclaimer.ts
- src/providers/historia-salud/categorias.ts
- src/providers/paciente.ts
https://proyectos.andes.gob.ar/browse/AM-49
https://proyectos.andes.gob.ar/browse/AM-51
1. Se agrega la opción de Mi Historia de Salud a la pantalla principal
2. Podes acceder a las distintas categorías, y descarga los adjuntos relacionados a los registros si corresponde.
https://gist.github.com/juuliotero/317fffa6ae571d8ac6cfa4b40d9ce10b
https://gist.github.com/juuliotero/a7d6dc8ee10d1c9b49cfd25a953f8604
> APP-MOBILE: listado de certificados

- Dockerfile
https://proyectos.andes.gob.ar/browse/AM-58
1. Se agrega dockerfile para la app-mobile
> AM: dockerfile

- src/pages/home/home.html
- src/pages/home/home.scss
- src/theme/main.scss
https://proyectos.andes.gob.ar/browse/AM-56
1.
> mobile-app: reposiciona items menu

- Dockerfile
- src/environments/environment.ts.example
Corrige el routing a la API en el environment.example para correr en Jenkins
1. 
2. 
3.
> Fix: environment API route

- .circleci/config.yml
- Dockerfile
- config.xml
- ionic.config.json
- package-lock.json
- package.json
- src/app/ads/ads.module.ts
- src/environments/environment.ts.example
Se agrega versionado de package en script
> Versionado config

- Dockerfile
- angular.json
- src/app/home/home.page.html
- src/environments/environment.ts.example
agrega mobile a href
1. 
2. 
3.
> fix(mobile): Corrige href

- angular.json
- ionic.config.json
- package.json
- src/app/pages/profesional/mpi/registro-paciente/registro-paciente.ts
- src/app/pages/profesional/mpi/scan-documento/scan-documento.html
- src/index.html
- src/providers/paciente-mpi.ts
https://proyectos.andes.gob.ar/browse/AM-119
1. Se actualizan las rutas de paciente
2. Se arreglan errores al guardar pacientes escaneados
> MPI: arreglo al escanear un DNI como profesional

- README.md
- config.xml
- Soporte para Android SDK versión 19 como mínima (actual 22)
- Documentar el proceso de build 
1. Se modificó [config.xml](https://raw.githubusercontent.com/andes/mobile-app/edde120a8b1f8e0b775bd1d5751a2dc06963cec4/config.xml) configurando soporte a versiones 19 a 30 de Android SDK
2. Se documentó el proceso de build en [README.md](https://raw.githubusercontent.com/andes/mobile-app/edde120a8b1f8e0b775bd1d5751a2dc06963cec4/README.md)
> Documentacion de build y soporte para SDK 19 a 30

- README.md
Documentar instalación de requerimientos y configuraciones.
1. Instalación y configuración de paquetes y programas necesarios (Java, Gradle, Android SDK)
2. Instalación de requerimientos globales del proyecto (Ionic 5, Cordova 10, cordova-res)
> docs(Android/Linux): instalación de requerimientos

- src/app/pages/profile/paciente/donde-vivo-donde-trabajo/donde-vivo-donde-trabajo.ts
https://proyectos.andes.gob.ar/browse/AM-89
1. Permitir que un paciente actualice datos personales de sus familiares
> AM: arreglo de error al actualizar datos de un familiar

- src/app/home/home.page.html
- src/app/pages/login/organizaciones/organizaciones.ts
- src/app/providers/events.service.ts
- src/providers/constantes.ts
- src/providers/tablas-maestras.ts
https://proyectos.andes.gob.ar/browse/AM-95
1. Suma opción al menú para permitir al profesional cambiar de organización
2. Limpieza de código
> AM: permitir al profesional cambiar de organización

- src/app/home/home.page.html
- src/app/pages/laboratorios/laboratorios.page.html
- src/app/pages/laboratorios/laboratorios.page.ts
https://proyectos.andes.gob.ar/browse/AM-52
1. Habilita la consulta de laboratorios para familiares
> AM: permitir ver laboratorios de familiar

- src/app/home/home-page.ts
- src/app/home/home.page.html
- src/app/pages/mis-familiares/mis-familiares.page.html
- src/app/pages/mis-familiares/mis-familiares.page.ts
https://proyectos.andes.gob.ar/browse/AM-130
1. Cuando accedo como un familiar, me reemplaza el botón del home de 'Mis familiares' por 'Salir de Familiar'
2. Si se llega al listado de familiares como un familiar, muestra solo al paciente principal.
> AM: visualización de familiares hasta un nivel

- config.xml
- ionic.config.json
- package-lock.json
- package.json
- src/app/pages/login/informacion-validacion/informacion-validacion.html
- src/app/pages/login/informacion-validacion/informacion-validacion.ts
- src/app/pages/login/login.module.ts
- src/app/pages/login/login.page.html
- src/app/pages/login/login.page.ts
- src/global.scss
- src/providers/paciente.ts
- src/theme/main.scss
https://proyectos.andes.gob.ar/browse/AM-129
1. Se crea un formulario para permitir que los usuarios se registren solos en la app
> AM: permitir registro de usuarios desde la app

- src/app/pages/laboratorios/laboratorios.page.html
- src/providers/toast.ts
https://proyectos.andes.gob.ar/browse/AM-147
1. Se arregla el service de toasts, para que tengan todos su color correspondiente
2. Además se hizo un pequeño fix en el botón "ver más" en laboratorios (sólo visible si hay más de 10 items)
> Fix toasts y "ver más" laboratorios

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/providers/events.service.ts
- src/components/agenda-item/agenda-item.ts
- src/providers/errorReporter.ts
https://proyectos.andes.gob.ar/browse/AM-144
1. Se refactorizó el servicio que envía reportes (sugerencias, errores) para que pueda enviar mensajes personalizados, se comprueba que la plataforma sea la correcta
2. Se instalaron plugins de cordova de captura de pantalla y de envío de emails
2. La opción ahora se ubica dentro del menú principal
3. Antes de enviar se da información y se pone en conocimiento al usuario sobre qué se va a enviar
4. Luego del envío se muestra un mensaje de envío satisfactorio.
5. **Importante:** sólo funciona desde un dispositivo, ver abajo información sobre plugins
```
// Plugin screenshots:
ionic cordova plugin add com.darktalker.cordova.screenshot
npm install @ionic-native/screenshot
// Plugin envío de email por app externa:
ionic cordova plugin add …
```
> Sugerencias y errores

- src/app/pages/profesional/rup-adjuntar/rup-adjuntar.ts
https://proyectos.andes.gob.ar/browse/AM-132
1. Permitir agregar archivos a RUP con extensión en mayúscula
> AM: permitir adjuntar imágenes en rup con extensión en mayúscula

- src/app/home/home-page.ts
- src/app/home/home.page.html
https://proyectos.andes.gob.ar/browse/AM-126
1. Cuando se cierra sesión desde home, no mostrar el nombre del usuario en el bienvenido
> AM: si cierro sesión desde home, limpiar nombre del bienvenido

- src/app/pages/login/informacion-validacion/informacion-validacion.html
- src/app/pages/login/informacion-validacion/informacion-validacion.ts
- src/app/pages/login/login.page.html
- src/app/pages/login/login.page.ts
- src/app/pages/login/recuperar-password/recuperar-password.html
- src/app/pages/login/recuperar-password/recuperar-password.ts
https://proyectos.andes.gob.ar/browse/AM-148
1. Se agrega loader (circulitos) cuando se toca en botón "Registrarme"
> feat(registro): se agrega loader

- src/app/pages/profesional/agendas/agenda-detalle/agenda-detalle.html
- src/app/pages/profesional/agendas/agenda-detalle/agenda-detalle.ts
- src/components/agenda-item/agenda-item.ts
https://proyectos.andes.gob.ar/browse/AM-115
1. Como profesional, al acceder a Mis Agendas y acceder a alguna donde al menos un paciente tenga asistencia se arregla la visualización de los datos
> AM: arreglo de visualización de turnos de agendas

- src/app/pages/login/login.page.html
- src/app/pages/login/login.page.ts
https://proyectos.andes.gob.ar/browse/AM-151
1. Se suma un botón de 'Ingresar código de activación' que cambie los labels del formulario del login
> AM: diferenciar entre login y activación de cuenta

- src/app/pages/mis-familiares/mis-familiares-routing.module.ts
- src/app/pages/mis-familiares/mis-familiares.module.ts
- src/app/pages/mis-familiares/mis-familiares.page.html
- src/app/pages/mis-familiares/mis-familiares.page.ts
- src/app/pages/mis-familiares/registro-familiar.html
- src/app/pages/mis-familiares/registro-familiar.ts
- src/providers/paciente.ts
https://proyectos.andes.gob.ar/browse/AM-153
1. Permitir al usuario registrar hijos menores a 11 años desde la aplicación
> AM: registro de hijos menores a 11 años

- config.xml
- ionic.config.json
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/pages/historia-salud/categorias/detalle-categoria.html
- src/app/pages/historia-salud/categorias/detalle-categoria.ts
- src/app/pages/historia-salud/historia-salud.module.ts
- src/app/pages/laboratorios/laboratorios.page.ts
- src/app/pages/mis-familiares/mis-familiares.page.html
- src/app/pages/profesional/rup-adjuntar/rup-adjuntar.html
- src/providers/descarga-archivos.ts
- src/providers/paciente.ts
https://proyectos.andes.gob.ar/browse/AM-155
1. Se agregó metodo que descarga la prestación pegandole a la ruta de descargas
2. Usa plugin de transferencia y apertura de archivos nativa, compatible con Android y iOS
3. Dependiendo del campo busquedaPor de la categoría utiliza distintas rutas para obtener los datos de la huds del paciente
> feat(certificados): Implementa descarga de prestación o registro

- src/app/pages/datos-utiles/campanias/campanias-list.html
- src/app/pages/datos-utiles/campanias/detalle/campania-detalle.html
- src/theme/main.scss
https://proyectos.andes.gob.ar/browse/MISC-173
1. Se centralizó la imagen de las campañas de salud y se eliminaron las fechas de vigencia de la misma antes y durante la descripción de las campañas.
> refactor(MISC-173) Modificando campañas de salud

- src/app/home/home-page.ts
- src/app/pages/turnos/buscar/turnos-buscar.ts
- src/app/pages/turnos/calendario/turnos-calendario.html
- src/app/pages/turnos/calendario/turnos-calendario.ts
- src/app/pages/turnos/prestaciones/turnos-prestaciones.ts
- src/app/pages/turnos/turnos.page.ts
https://proyectos.andes.gob.ar/browse/AM-156
1. Cambios en navegación y parametros entre las pantallas de turnos
2. Cambios en método que trae las agendas para que envíe datos del paciente y traiga nuevas configuraciones
> feat(AM): Permitir acceder a turnos mediante reglas

- src/app/app.component.ts
- src/app/app.module.ts
- src/app/pages/datos-utiles/centros-salud/centros-salud.html
- src/app/pages/datos-utiles/centros-salud/centros-salud.ts
https://proyectos.andes.gob.ar/browse/AM-172
1. Se implementa funcionalida "volver atrás" con el botón del dispostivo para ese propósito
2. Además se implementa un cierre de la aplicación si se está en la Home, con confirmación de por medio.
> feat(back-button): se implementa back button de sistema

- config.xml
- ionic.config.json
- package-lock.json
- package.json
Actualiza a versión 4.8.0
1. update version
> Update to version 4.8.0

- src/app/pages/datos-utiles/feed-noticias/feed-noticias.ts
- src/app/pages/login/informacion-validacion/informacion-validacion.html
- src/app/pages/login/informacion-validacion/informacion-validacion.ts
- src/environments/environment.ts.example
- src/providers/errorReporter.ts
https://proyectos.andes.gob.ar/browse/AM-165
> feat(AM):eliminación hardcodeo de email

- src/app/pages/mis-familiares/mis-familiares.page.ts
https://proyectos.andes.gob.ar/browse/AM-181
1. Se agrego un control cuando se selecciona un familiar para que te redirija a la pantalla de mis familiares solo en el caso de que sea hijo/a menor a 11 años.
> feat(MOBILE):control de edad en mis familiares

- src/app/pages/profesional/mpi/registro-paciente/registro-paciente.html
- src/app/pages/profesional/profile/profile-profesional.html
- src/app/pages/profile/paciente/profile-paciente/profile-paciente.html
- src/app/pages/vacunas/vacunas-detalle.page.html
- src/app/pages/vacunas/vacunas-detalle.page.scss
- src/app/pages/vacunas/vacunas-detalle.page.ts
- src/app/pages/vacunas/vacunas-routing.module.ts
- src/app/pages/vacunas/vacunas.module.ts
- src/app/pages/vacunas/vacunas.page.html
- src/app/pages/vacunas/vacunas.page.ts
https://proyectos.andes.gob.ar/browse/AM-174
> feat(MOBILE):Detalle de vacunación

- src/app/pages/datos-utiles/faq/faq.html
https://proyectos.andes.gob.ar/browse/AM-187
1. También se hizo un relevamiento para incorporar nuevas preguntas frecuentes
> MOBILE - quita última pregunta frecuente

- src/app/pages/login/informacion-validacion/informacion-validacion.ts
- src/app/pages/mis-familiares/mis-familiares.module.ts
- src/app/pages/mis-familiares/registro-familiar.html
- src/app/pages/mis-familiares/registro-familiar.ts
- src/app/pages/profesional/mpi/scan-documento/scan-documento.ts
- src/providers/config-scan.ts
https://proyectos.andes.gob.ar/browse/AM-161
1. En registro de familiar se agrega la funcionalidad del scan
> MOBILE - scan para registro de familiar

- src/providers/network.ts
https://proyectos.andes.gob.ar/browse/AM-191
> MOBILE - toast conexión

- src/app/home/home-page.ts
https://proyectos.andes.gob.ar/browse/AM-192
> MOBILE - Background home

- src/app/pages/turnos/calendario/turnos-calendario.html
- src/app/pages/turnos/calendario/turnos-calendario.ts
- src/app/pages/turnos/detalles/turno-detalle.html
- src/app/pages/turnos/detalles/turno-detalle.ts
- src/components/turno-item/turno-item.html
https://proyectos.andes.gob.ar/browse/CIT-113
1. en turno detalle se agrega botón para acceder al turno virtual si es de ese tipo.
2. 
3. 
- [] No
> feat(citas):  consultorio virtual

- src/app/pages/gestion/acciones/acciones.html
- src/app/pages/gestion/listado-detalle/listado-detalle.html
- src/app/pages/gestion/listado-detalle/listado-detalle.ts
- src/app/pages/gestion/mapa-detalle/mapa-detalle.scss
No se visualizaban los titlos de los iconos del footer ni de periodicidad
1. Se agregaron clases para que se visualicen los títulos
> feat(Gestion): Agrega clases a titulos de acciones

- src/app/pages/mis-familiares/registro-familiar.html
- src/app/pages/mis-familiares/registro-familiar.ts
https://proyectos.andes.gob.ar/browse/AM-209
1. Solo se permite el registro de un familiar escaneando su dni
> AM: registro de familiar con scan

- src/app/app.component.ts
- src/app/pages/gestion/acciones/acciones.ts
- src/app/pages/gestion/gestion.page.ts
- src/providers/datos-gestion/datos-gestion.provider.ts
https://proyectos.andes.gob.ar/browse/AM-213
1. Se hizo un refactor en la carga de fechas de periodicidad
2. Se aplicó un fix en el uso de @Inputs que generaban errores
> Fix en carga de fechas de periodicidades

- package.json
- src/app/app.module.ts
- src/app/pages/turnos/detalles/turno-detalle.html
- src/app/pages/turnos/detalles/turno-detalle.ts
- src/app/pages/turnos/historial/historial-turnos.html
- src/app/pages/turnos/historial/historial-turnos.ts
- src/app/pages/turnos/notificaciones/notificacion-turno.page.html
- src/app/pages/turnos/notificaciones/notificacion-turno.page.ts
- src/app/pages/turnos/prestaciones/turnos-prestaciones.ts
- src/app/pages/turnos/turnos-routing.module.ts
- src/app/pages/turnos/turnos.module.ts
- src/global.scss
- src/providers/auth/device.ts
- src/providers/constantes.ts
- src/providers/locations/checkLocation.ts
https://proyectos.andes.gob.ar/browse/AM-189
1. Se implementó una página para mostrar detalles de una notificación de un cambio en un turno
2. Se accede desde una push notification
3. En esta versión implementa las suspensiones de turnos
4. Se hizo un refactor del provider de GPS para poder redireccionar al paciente a la sección de turnos ("se suspendió tu turno, podés sacar uno nuevo")
> Detalles de turno (suspensión)

- src/app/pages/turnos/detalles/turno-detalle.html
- src/app/pages/turnos/prestaciones/turnos-prestaciones.ts
https://proyectos.andes.gob.ar/browse/AM-194
1. Mostrar prestación si tengo un turno suspendido en otra agenda
> AM: ver prestación si tengo un turno suspendido

- src/app/app.component.ts
- src/providers/auth/auth.ts
[ ](https://proyectos.andes.gob.ar/browse/AM-238)
1. Omite recuperar la sesion anterior en cada inicio de la aplicación
> AM - Nueva sesion en cada inicio de app

- src/app/pages/historia-salud/categorias/detalle-categoria.html
- src/app/pages/historia-salud/categorias/detalle-categoria.ts
- src/providers/paciente.ts
https://proyectos.andes.gob.ar/browse/AM-259
1. Se agrega categorias de cdas (Pap y Mamografía) y se trabaja la descarga de pdfs.
> AM - Visualizacion de otros estudios complementarios

- resources/android/xml/network_security_config.xml
- src/app/pages/profesional/mis-matriculas/comprobante-profesional.html
- src/app/pages/profesional/mis-matriculas/comprobante-profesional.ts
- src/app/pages/profesional/mis-matriculas/datos-profesional.ts
- src/app/pages/profesional/mis-matriculas/firma-profesional.ts
- src/app/pages/profesional/mis-matriculas/foto-profesional.ts
- src/providers/profesional.ts
https://proyectos.andes.gob.ar/browse/MAT-87
1. Se modifica el reuquest a la ruta nueva para actualizar domicilios.
> MAT - Nueva ruta para modificar domicilios

- src/providers/auth/device.ts
https://proyectos.andes.gob.ar/browse/AM-237
1. Notifica al usuario sobre la cancelacion de la solicitud de adjuntar un documento y vuelve al inicio de rup.
- [X ] No corresponde
> RUP -  Error en Adjuntos RUP

- src/app/pages/mis-familiares/mis-familiares.page.html
- src/app/pages/mis-familiares/mis-familiares.page.ts
- src/app/pages/mis-familiares/registro-familiar.html
https://proyectos.andes.gob.ar/browse/AM-256
1.  De relación paciente, se permite hasta 13 años los pacientes hijos, en lo casos de ingresar al perfil y de registrarlo después de escanear documento.
> AM - Cambiar edad para usar perfil Hijo 

- src/app/pages/profile/paciente/contacto/profile-contacto.html
- src/app/pages/profile/paciente/contacto/profile-contacto.ts
- src/app/pages/profile/paciente/donde-vivo-donde-trabajo/donde-vivo-donde-trabajo.html
- src/app/pages/profile/paciente/donde-vivo-donde-trabajo/donde-vivo-donde-trabajo.ts
- src/app/pages/profile/paciente/profile-paciente/profile-paciente.html
- src/app/pages/profile/paciente/profile-paciente/profile-paciente.scss
- src/app/pages/profile/paciente/profile-paciente/profile-paciente.ts
- src/app/pages/profile/paciente/tab-view-profile.html
- src/providers/toast.ts
https://proyectos.andes.gob.ar/browse/AM-267
1. Al momento de actualizar el domicilio, se modifican los campos de provincia y localidad por select.
2. En el ts se trabajo con solicitudes a la bd, para los datos de provincia y sus respectivas localidades.
3. Se agrega modal para solicitar confirmación de actualización.
> AM - Editar domicilio paciente

- src/app/pages/turnos/prestaciones/turnos-prestaciones.html
Cambia mensaje al momento de no encontrar agendas o turnos disponibles
> fix(AM): Cambia mensaje al no encontrar turnos disponibles

- src/app/pages/turnos/historial/historial-turnos.html
- src/app/pages/turnos/historial/historial-turnos.ts
- src/app/pages/turnos/turnos.page.html
https://proyectos.andes.gob.ar/browse/AM-277
1.  Se modifica el storage para visualizar el historial de turnos.
2.  Se analiza el acceso en la sección "Mis Turnos".
> AM - Historial de turnos

- config.xml
- src/app/app.component.ts
- src/app/home/home-page.ts
- src/app/home/home-routing.module.ts
- src/app/home/home.module.ts
- src/app/home/home.page.scss
- src/app/home/new-home.page.html
- src/app/home/new-home.page.ts
- src/app/pages/login/disclaimers/accept-disclaimer.ts
- src/app/pages/login/login-routing.module.ts
- src/app/pages/login/login.module.ts
- src/app/pages/login/login.page.html
- src/app/pages/login/login.page.scss
- src/app/pages/login/login.page.ts
- src/app/pages/login/loginProfesional.page.html
- src/app/pages/login/loginProfesional.page.ts
- src/app/pages/login/organizaciones/organizaciones.ts
- src/app/pages/profile/account/profile-account.ts
- src/app/pages/profile/paciente/profile-paciente/profile-paciente.ts
- src/app/pages/turnos/calendario/turnos-calendario.ts
- src/app/pages/turnos/detalles/turno-detalle.ts
- src/app/providers/events.service.ts
- src/theme/main.scss
[https://proyectos.andes.gob.ar/browse/AM-271](https://proyectos.andes.gob.ar/browse/AM-271)
1. 
2. 
3.
> FEAT(MAIN): Separar inicio de paciente y profesional

- src/app/pages/profile/paciente/profile-paciente/edit-alias/edit-alias-routing.module.ts
- src/app/pages/profile/paciente/profile-paciente/edit-alias/edit-alias.module.ts
- src/app/pages/profile/paciente/profile-paciente/edit-alias/edit-alias.page.html
- src/app/pages/profile/paciente/profile-paciente/edit-alias/edit-alias.page.ts
- src/app/pages/profile/paciente/profile-paciente/edit-genero/edit-genero/edit-genero-routing.module.ts
- src/app/pages/profile/paciente/profile-paciente/edit-genero/edit-genero/edit-genero.module.ts
- src/app/pages/profile/paciente/profile-paciente/edit-genero/edit-genero/edit-genero.page.html
- src/app/pages/profile/paciente/profile-paciente/edit-genero/edit-genero/edit-genero.page.ts
- src/app/pages/profile/paciente/profile-paciente/profile-paciente.html
- src/app/pages/profile/paciente/profile-paciente/profile-paciente.scss
- src/app/pages/profile/paciente/profile-paciente/profile-paciente.ts
- src/app/pages/profile/profile-routing.module.ts
- src/providers/constantes.ts
https://proyectos.andes.gob.ar/browse/AM-306
1. Se crean componentes para editar nombre y género
2. En edición de genero se edita seleccionando de un select con los generos de DB
> AM - Seleccionar género

- config.xml
- package-lock.json
- package.json
- scripts/remove_permissions.js
https://proyectos.andes.gob.ar/browse/AM-286
1. Se agregan los permisos, que se estaban. eliminado a fuerza... android 13 se vuelven a agregar: 
android.permission.WRITE_EXTERNAL_STORAGE
android.permission.READ_EXTERNAL_STORAGE
> fix(MAIN): corrige error al sacar fotos: rup y matriculaciones

- .circleci/config.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
Cambiar version de node en workfllow
> chore: Cambiar version de node para build

- src/app/pages/historia-salud/historia-salud-routing.module.ts
- src/app/pages/historia-salud/historia-salud.module.ts
- src/app/pages/historia-salud/historia-salud.page.ts
- src/app/pages/historia-salud/recetas/detalle-receta/detalle-receta.html
- src/app/pages/historia-salud/recetas/detalle-receta/detalle-receta.scss
- src/app/pages/historia-salud/recetas/detalle-receta/detalle-receta.ts
- src/app/pages/historia-salud/recetas/recetas.html
- src/app/pages/historia-salud/recetas/recetas.scss
- src/app/pages/historia-salud/recetas/recetas.ts
- src/providers/historia-salud/recetas.ts
- src/theme/main.scss
https://proyectos.andes.gob.ar/browse/AM-314
1. Implementación de visualización de recetas
- [] No
> AM - implementacion de visualización de recetas

- src/app/pages/laboratorios/laboratorios.page.html
- src/app/pages/laboratorios/laboratorios.page.ts
- src/global.scss
- src/providers/library-services/descarga-archivos.ts
- src/providers/paciente.ts
https://proyectos.andes.gob.ar/browse/AM-330
1. Agregar al listado de laboratorios los que vienen de SIL2
2. Implementación de filtro por fechas en el listado de laboratorios
3. Limpieza de código
> feat: descarga de laboratorios desde sil2
